//! Generates the Ink/Stitch compatibility contract page from `conformance/inkstitch-params.toml`.
//!
//! The data file holds facts only (names, types, units, defaults, applicability, phases); Ink/Stitch's
//! descriptions are GPL text and are never copied. From M3 the registry adds a status column.

use serde::Deserialize;

/// Where the page is written, relative to the repository root.
pub const PAGE: &str = "docs/src/design/inkstitch-compat-contract.md";
/// The data file, relative to the repository root.
pub const DATA: &str = "conformance/inkstitch-params.toml";

#[derive(Deserialize)]
struct Contract {
    #[serde(default)]
    lock_ids: Vec<String>,
    param: Vec<Param>,
    #[serde(default)]
    method: Vec<Method>,
}

#[derive(Deserialize)]
struct Param {
    element: String,
    name: String,
    #[serde(rename = "type")]
    kind: String,
    unit: String,
    default: String,
    applies_to: Vec<String>,
    phase: String,
    milestone: String,
}

#[derive(Deserialize)]
struct Method {
    param: String,
    value: String,
    phase: String,
    milestone: String,
}

const SECTIONS: &[(&str, &str)] = &[
    ("common", "All stitch types (ties, locks, trims, stops)"),
    ("stroke", "Strokes: running, ripple, zigzag, manual"),
    ("satin", "Satin columns"),
    ("fill", "Fills"),
    ("clone", "Clones (`<use>`)"),
];

const INTRO: &str = "\
<!-- GENERATED by `cargo xtask docs` from conformance/inkstitch-params.toml. Do not edit by hand. -->

# Ink/Stitch compatibility contract

The parameters an Ink/Stitch SVG can carry, as `inkstitch:<name>` attributes, and when StitchCraft
supports each one. This is the interoperability contract: StitchCraft's registry uses these names as
its keys so files move between the tools unchanged ([ADR-0001](adr/0001-license-and-clean-room.md)).

- **Source:** Ink/Stitch `main` at `d59c9ab` (2026-09-17), 145 `@param` declarations.
- **Facts only:** names, types, units, defaults and applicability. Ink/Stitch's descriptions are GPL text
  and are not copied; StitchCraft's own help text lives in the [parameter registry](params.md).
- **Machine-readable source:** `conformance/inkstitch-params.toml`; this page is generated from it by
  `cargo xtask docs`, and `cargo xtask docs --check` fails if the two disagree. From M3 the page gains a
  *Status* column (planned / supported / deviates) from the registry, and a milestone cannot close with
  its rows still planned.
- **Phase** is when the parameter's stitch type lands ([roadmap](../plan/roadmap.md)). `—` means no default
  (the value is derived from another parameter or the shape); `computed` means the default is an expression.
";

/// Renders the page from the data file's text.
pub fn render(data: &str) -> Result<String, String> {
    let contract: Contract = toml::from_str(data).map_err(|e| format!("{DATA}: {e}"))?;
    let mut md = String::from(INTRO);
    for (key, title) in SECTIONS {
        md.push_str(&format!("\n## {title}\n\n| Attribute | Type | Unit | Default | Applies to | Phase |\n|---|---|---|---|---|---|\n"));
        for p in contract.param.iter().filter(|p| p.element == *key) {
            let applies = if p.applies_to.is_empty() {
                "all".to_string()
            } else {
                p.applies_to.iter().map(|a| format!("`{a}`")).collect::<Vec<_>>().join(", ")
            };
            md.push_str(&format!(
                "| `{}` | {} | {} | {} | {applies} | {} ({}) |\n",
                p.name,
                p.kind,
                p.unit.replace('|', "\\|"),
                p.default,
                p.phase,
                p.milestone
            ));
        }
    }
    md.push_str(
        "\n## Method identifiers\n\nThe values the method parameters take (`stroke_method`, `satin_method`, `fill_method`), with phases:\n\n",
    );
    md.push_str("| Parameter | Value | Phase |\n|---|---|---|\n");
    for m in &contract.method {
        md.push_str(&format!("| `{}` | `{}` | {} ({}) |\n", m.param, m.value, m.phase, m.milestone));
    }
    let locks = contract.lock_ids.iter().map(|l| format!("`{l}`")).collect::<Vec<_>>().join(", ");
    md.push_str(&format!(
        "\nLock stitch identifiers (`lock_start`, `lock_end`): {locks}. StitchCraft accepts every identifier; the shapes are its own\n\
         designs with the same intent, recorded as a deviation in the [conformance](conformance.md) deviations ledger.\n"
    ));
    md.push_str(&format!("\n_{} parameter declarations._\n", contract.param.len()));
    Ok(md)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_sections_methods_and_counts() {
        let data = r#"
lock_ids = ["half_stitch"]
[[param]]
element = "fill"
name = "row_spacing_mm"
type = "float"
unit = "mm"
default = "0.25"
applies_to = ["tatami_fill"]
phase = "P1"
milestone = "M5"
[[method]]
param = "fill_method"
value = "tatami_fill"
phase = "P1"
milestone = "M5"
"#;
        let page = render(data).unwrap();
        assert!(page.contains("| `row_spacing_mm` | float | mm | 0.25 | `tatami_fill` | P1 (M5) |"));
        assert!(page.contains("| `fill_method` | `tatami_fill` | P1 (M5) |"));
        assert!(page.contains("_1 parameter declarations._"));
    }

    #[test]
    fn bad_data_is_an_error() {
        assert!(render("param = 3").is_err());
    }
}
