//! Generates the user reference pages from the registries they describe, so the documentation cannot
//! drift from the code: machine profiles, file formats, test sheets, diagnostic codes and the command
//! line (`docs/src/design/docs-pipeline.md`). `cargo xtask docs` writes them; `--check` fails when one
//! is stale.

use std::fmt::Write as _;

use clap::CommandFactory;
use stitchcraft_cli::cli::{self, Cli};
use stitchcraft_cli::commands::{self, counts};
use stitchcraft_core::{Code, Severity};
use stitchcraft_engine::testsheets::SHEETS;
use stitchcraft_plan::profiles::BUILTIN;
use stitchcraft_plan::{FormatId, TrimSupport};
use stitchcraft_render::Settings;

use crate::{shots, util};

const REFERENCE: &str = "docs/src/user/reference";

/// Every generated reference page: (path relative to the repository root, content).
pub fn pages() -> Result<Vec<(String, String)>, String> {
    Ok([
        (format!("{REFERENCE}/profiles.md"), profiles()),
        (format!("{REFERENCE}/formats.md"), formats()),
        (format!("{REFERENCE}/test-sheets.md"), test_sheets()?),
        (format!("{REFERENCE}/diagnostics.md"), diagnostics()),
        (format!("{REFERENCE}/cli.md"), cli()),
    ]
    .into_iter()
    .chain(examples()?)
    .collect())
}

fn header(title: &str, source: &str) -> String {
    format!("<!-- Generated by `cargo xtask docs` from {source}. Edit the source, not this page. -->\n\n# {title}\n\n")
}

fn mm(value: f64) -> String {
    format!("{value} mm")
}

fn profiles() -> String {
    let mut out = header("Machine profiles", "`stitchcraft-plan/src/profiles/`");
    out.push_str(
        "A profile holds the facts about one machine and hoop that decide what StitchCraft may ask of it. Its values are \
         machine facts: they change only with a sew-out report that justifies them, and each profile says where its values \
         come from. `stitch profiles` prints the same list.\n",
    );
    for p in BUILTIN {
        let _ = writeln!(out, "\n## `{}`\n\n{}\n", p.id, p.name);
        let _ = writeln!(out, "| Fact | Value |\n|---|---|");
        let _ = writeln!(out, "| Hoop (sewing field) | {} × {} |", p.hoop.width.get(), mm(p.hoop.height.get()));
        if let Some(c) = p.comfort {
            let _ = writeln!(
                out,
                "| Comfort zone | {} × {} — larger designs get [`SC-W0702`](diagnostics.md#sc-w0702) |",
                c.width.get(),
                mm(c.height.get())
            );
        }
        let _ = writeln!(out, "| File format | {} |", p.format.name());
        let _ = writeln!(out, "| Stitch length | {} to {} (lock stitches from 0.2 mm) |", mm(p.min_stitch.get()), mm(p.max_stitch.get()));
        let trims = match p.trims {
            TrimSupport::Command => "the format's trim command".to_string(),
            TrimSupport::LongJumps(length) => format!("cuts jumps longer than {} by itself", mm(length.get())),
            TrimSupport::None => "none: cut jump threads by hand".to_string(),
        };
        let _ = writeln!(out, "| Trims | {trims} |");
        let _ = writeln!(out, "| Thread palette | {} |", p.palette.palette().name);
        let _ = writeln!(out, "\n**Evidence.** {}", p.evidence);
    }
    out
}

fn formats() -> String {
    let mut out = header("File formats", "`FormatId` in `stitchcraft-plan` and the writers in `stitchcraft-formats`");
    out.push_str(
        "The machine-file formats StitchCraft writes. How each is encoded, and why, is in the \
         [machine formats design](../../design/formats.md).\n\n| Format | Extension | Colour changes and stops | Colours stored as |\n|---|---|---|---|\n",
    );
    for f in FormatId::ALL {
        let colours = match f.palette() {
            Some(id) => format!("indices into the {} palette (nearest colour, CIEDE2000)", id.palette().name),
            None => "nothing: the machine pauses and the operator loads the next thread".to_string(),
        };
        let _ = writeln!(out, "| {} | `.{}` | at most {} | {colours} |", f.name(), f.extension(), f.max_color_changes());
    }
    out
}

fn test_sheets() -> Result<String, String> {
    let mut out = header("Test sheets", "`stitchcraft-engine/src/testsheets/` and the `stitch` shots in `docs/shots.toml`");
    out.push_str(
        "Designs drawn in code for the [machine checkpoints](../../plan/machine-testing.md). Write one with \
         `stitch testsheet <id> --profile brother-200x200 -o <id>.pes`; the command also prints what to check after \
         sewing it, as listed here. The pictures are previews: they show what the machine will sew, \
         including jump threads it leaves for you to cut.\n",
    );
    let shots = shots::load(&util::root())?;
    for sheet in SHEETS {
        let plan = sheet.plan().map_err(|e| format!("{}: {e}", sheet.id))?;
        let _ = writeln!(out, "\n## {} — {}\n", sheet.id, sheet.title);
        if let Some(b) = plan.bounds() {
            let _ = writeln!(out, "{:.1} × {:.1} mm · {}\n", b.width(), b.height(), counts(&plan));
        }
        for shot in shots.iter().filter(|s| s.kind == "stitch" && s.sheet.as_deref() == Some(sheet.id)) {
            let _ = writeln!(out, "![{}](../../images/generated/{}.png)\n", shot.alt, shot.id);
        }
        let threads: Vec<String> = plan
            .color_entries()
            .iter()
            .map(|e| format!("{}{}", e.thread.name.as_deref().unwrap_or("unnamed"), if e.stop { " (stop)" } else { "" }))
            .collect();
        let _ = writeln!(out, "Threads: {}.\n\nAfter sewing, check:\n", threads.join(", "));
        for check in sheet.checks {
            let _ = writeln!(out, "- {check}");
        }
    }
    Ok(out)
}

fn diagnostics() -> String {
    let mut out = header("Diagnostic codes", "the registry in `stitchcraft-core/src/diag.rs`");
    out.push_str(
        "Every problem StitchCraft reports has a code. `E` codes are errors (nothing is written), `W` codes are \
         warnings (the file is written), `I` codes are information. `stitch explain <code>` prints the same \
         explanation in the terminal. Codes are never reused.\n\n| Code | Severity | Title |\n|---|---|---|\n",
    );
    for code in Code::ALL {
        let _ = writeln!(out, "| [`{}`](#{}) | {} | {} |", code.id(), code.id().to_ascii_lowercase(), severity(code.severity()), code.title());
    }
    for code in Code::ALL {
        let _ = writeln!(out, "\n## {}\n\n**{}** — {}\n\n{}", code.id(), severity(code.severity()), code.title(), code.explanation());
    }
    out
}

fn severity(s: Severity) -> &'static str {
    match s {
        Severity::Error => "Error",
        Severity::Warning => "Warning",
        Severity::Info => "Info",
    }
}

fn cli() -> String {
    let mut out = header("Command line", "the `clap` definition in `apps/stitchcraft-cli/src/cli.rs`");
    out.push_str("`stitch` is StitchCraft's command-line tool. Each section shows the command's own `--help`.\n");
    let mut command = Cli::command().term_width(100);
    let _ = writeln!(out, "\n## stitch\n\n```text\n{}```", command.render_long_help());
    for sub in command.get_subcommands_mut() {
        let name = sub.get_name().to_string();
        let mut sub = sub.clone().bin_name(format!("stitch {name}")).term_width(100);
        let _ = writeln!(out, "\n## stitch {name}\n\n```text\n{}```", sub.render_long_help());
    }
    out
}

/// What the tutorial's commands print, run for real so the docs show real output:
/// `stitch testsheet TS-01 …` and `stitch preview TS-01.pes …`.
fn examples() -> Result<Vec<(String, String)>, String> {
    let dir = std::env::temp_dir().join(format!("stitchcraft-docs-{}", std::process::id()));
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let (pes, png) = (dir.join("TS-01.pes"), dir.join("TS-01.png"));
    let testsheet = commands::testsheet::run(&cli::TestsheetArgs {
        sheet: Some("TS-01".into()),
        list: false,
        profile: Some("brother-200x200".into()),
        output: Some(pes.clone()),
        format: None,
    });
    let preview = commands::preview::run(&cli::PreviewArgs {
        file: pes.clone(),
        output: png.clone(),
        style: cli::PreviewStyle::Realistic,
        scale: Settings::DEFAULT_SCALE,
    });
    let _ = std::fs::remove_dir_all(&dir);
    let shown = |outcome: commands::Outcome, command: &str| {
        if outcome.status != commands::Status::Done {
            return Err(format!("{command} failed: {}", outcome.stderr));
        }
        let stdout = outcome.stdout.replace(&pes.display().to_string(), "TS-01.pes").replace(&png.display().to_string(), "TS-01.png");
        Ok(format!("$ {command}\n{stdout}"))
    };
    Ok(vec![
        (format!("{REFERENCE}/generated/testsheet-ts-01.txt"), shown(testsheet, "stitch testsheet TS-01 --profile brother-200x200 -o TS-01.pes")?),
        (format!("{REFERENCE}/generated/preview-ts-01.txt"), shown(preview, "stitch preview TS-01.pes -o TS-01.png")?),
    ])
}
